# Generated by Django 5.0.6 on 2024-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
