# Generated by Django 5.0.6 on 2024-07-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='buyer',
        ),
    ]
